apiVersion: v1
kind: Service
metadata:
  name: grade-submission-api
spec:
  # by default, without specifying the type, it is type: ClusterIP
  selector:
    app.kubernetes.io/instance: grade-submission-api
  ports:
  - port: 3000 # this is the service port, <service-name>:<service-port>
    targetPort: 3000 # this is the target port, the matching pod by selector above, with its target port